### ISSUE TITLE
consider adding an `.nvmrc`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/docs#5086]
**Is your feature request related to a problem? Please describe.**

Consider adding an nvmrc file to ensure contributors are using the same Node version as the build pipeline. While different node versions may not always cause an issue, they can print different error messages which would cause tests to fail locally. In the screenshot below I had corrected an error message as I was updating tests to find it error in the build workflow, where I was using Node 18 locally and the build workflow is set to use 14.

![image](https://user-images.githubusercontent.com/5033303/216671886-b3a273ca-7676-4ddf-838b-82f0baf0cad6.png)

This nvmrc file can also be used by the build workflow:

```yaml
- name: Setup Node.js 14.x
  uses: actions/setup-node@main
  with:
    node-version-file: '.nvmrc'
```

**Describe the solution you'd like**

add an nvmrc and/or contributing guidelines for suggested Node version

**Describe alternatives you've considered**

**Additional context**
