### ISSUE TITLE
On the Functions page, there should be somewhere talking about requirements for CICD builds

### ISSUE THREAD

**Issue by Bryson14** [aws-amplify/docs#5569]
**Describe the content issue**:
A clear and concise description of what the content issue is. Is there content missing or is there incorrect content?

on this page: https://docs.amplify.aws/cli/function/ it talks about all the different languages that can be used with lambda.

One issue that I ran into was that when the CICD Amplify was building, it would fail because the docker container running the build did not have go lang installed. It would be nice to have examples of what to include in the rebuild step for each language. For example, point out that if using te CICD, you can add:
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - yum install golang -y
        - mkdir ~/go_proj
        - export PATH=$PATH:/usr/local/go/bin
        - export GOPATH=$HOME/go_proj
        - export GOBIN=$GOPATH/bin
```
this would be a way to install and export go lang so the CICD runner could build my project.

**URL page where content issue is**:
