### ISSUE TITLE
Clarity to settle the amplify/cli AWS-EXPORTS.JS for good. in GEN1 and GEN2 apps

### ISSUE THREAD

**Issue by PixelJunkie33** [aws-amplify/docs#8031]
What is the best way to handle aws-exports.js file that is auto generated with the backend? Does this file contain sensitive data, should it remain in the public directory view or in a secret file for example :
```

 **You simply store aws-exports.js contents in an environment variable called "secretfile", and then use it inside amplify.yml like this

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - echo $secretfile > ./src/aws-exports.js
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/***
```
